Flownative:
  Neos:
    Trados:
      languageDimension: 'language'
      export:
        workspace: 'live'
        documentTypeFilter: 'Neos.Neos:Document'
        directory: 'Data/Trados/Export/'
      import:
        directory: 'Data/Trados/Import/'
